import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// VoiceMemoTranscriber — generated by AppFactoryKit appgen from niche "transcribe-voice".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum VoiceMemoTranscriberFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "VoiceMemoTranscriber",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "waveform",
                          title: "VoiceMemoTranscriber",
                          message: "Record/import audio → text + summary."),
                    .init(systemImage: "mic.fill",
                          title: "Go Pro",
                          message: "Unlimited minutes, summaries, export.")
                ],
                presentsPaywallOnFinish: true,
                accent: .pink
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock VoiceMemoTranscriber Pro",
                subheadline: "Unlimited minutes, summaries, export.",
                benefits: [
                    .init(systemImage: "infinity", title: "Unlimited minutes"),
                    .init(systemImage: "bolt.fill", title: "Summaries"),
                    .init(systemImage: "nosign", title: "Export")
                ],
                productIDs: ["transcribe-voice_yearly", "transcribe-voice_weekly"],
                highlightedProductID: "transcribe-voice_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .pink, heroSystemImage: "waveform")
            )
        )
        return AppFactory(config)
    }
}

@main
struct VoiceMemoTranscriberApp: App {
    @StateObject private var factory = VoiceMemoTranscriberFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.pink)
        }
    }
}
